let worldData = [
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "FORTRESS00_LINESAUF",
		guild_member_count: 45,
		max_guild_member_count: 45,
		guild_id: "1307410000020000005",
		guild_name: "百事可樂",
		guild_level: 36,
		guild_master_guid: "1107400000560000179",
		guild_master_gc_name: "엄지",
		guild_description: "해",
		ranking: 4,
		tax_dia: 2392,
		tax_ruby: 4050,
		trade_tax_rate: "1",
		shop_tax_rate: "20",
		craft_tax_rate: "30",
		territory_count: 2,
		territory_grade: "Fortress",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON00_AMINTA",
		guild_member_count: 45,
		max_guild_member_count: 45,
		guild_id: "1307220000000000008",
		guild_name: "KOREA",
		guild_level: 31,
		guild_master_guid: "1107200000000001051",
		guild_master_gc_name: "김가네",
		guild_description: "절대중립 라인마찰시 추방,1일 미접시 추방",
		ranking: 9,
		tax_dia: 2392,
		tax_ruby: 4050,
		trade_tax_rate: "1",
		shop_tax_rate: "20",
		craft_tax_rate: "30",
		territory_count: 1,
		territory_grade: "Fortress",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON00_KROHN",
		guild_member_count: 49,
		max_guild_member_count: 50,
		guild_id: "1307220000000000006",
		guild_name: "牛奶",
		guild_level: 52,
		guild_master_guid: "1107200000280000088",
		guild_master_gc_name: "매너",
		guild_description: "보스,컨텐츠즐기실 가족 모집. 토벌 11이상 문의",
		ranking: 1,
		tax_dia: 2391,
		tax_ruby: 4050,
		trade_tax_rate: "1",
		shop_tax_rate: "20",
		craft_tax_rate: "30",
		territory_count: 2,
		territory_grade: "Fortress",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON00_RONDO",
		guild_member_count: 49,
		max_guild_member_count: 50,
		guild_id: "1307220000000000006",
		guild_name: "牛奶",
		guild_level: 52,
		guild_master_guid: "1107200000280000088",
		guild_master_gc_name: "매너",
		guild_description: "보스,컨텐츠즐기실 가족 모집. 토벌 11이상 문의",
		ranking: 1,
		tax_dia: 7195,
		tax_ruby: 8100,
		trade_tax_rate: "3",
		shop_tax_rate: "20",
		craft_tax_rate: "30",
		territory_count: 2,
		territory_grade: "Castle",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON01_AMINTA",
		guild_member_count: 40,
		max_guild_member_count: 41,
		guild_id: "1307330000160000005",
		guild_name: "소작농마을",
		guild_level: 20,
		guild_master_guid: "1107300000160000232",
		guild_master_gc_name: "선량한소작농",
		guild_description: "아무나 환영합니다 어서오세용",
		ranking: 39,
		tax_dia: 0,
		tax_ruby: 0,
		trade_tax_rate: "0",
		shop_tax_rate: "20",
		craft_tax_rate: "30",
		territory_count: 1,
		territory_grade: "Garrison",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON01_KROHN",
		guild_member_count: 37,
		max_guild_member_count: 47,
		guild_id: "1313330000020000022",
		guild_name: "놀이동산",
		guild_level: 49,
		guild_master_guid: "1113300000020001195",
		guild_master_gc_name: "로티",
		guild_description: "편안한 분위기, 즐겁게 게임하실분 모셔요",
		ranking: 2,
		tax_dia: 0,
		tax_ruby: 0,
		trade_tax_rate: "0",
		shop_tax_rate: "20",
		craft_tax_rate: "30",
		territory_count: 2,
		territory_grade: "Garrison",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON01_LINESAUF",
		guild_member_count: 32,
		max_guild_member_count: 42,
		guild_id: "1317320000040000010",
		guild_name: "검은칼공작소",
		guild_level: 29,
		guild_master_guid: "1117300001420000077",
		guild_master_gc_name: "공작소공장장",
		guild_description: "일하고 보상받아가세요, 열심히 활동할 분은 귓 부탁드려",
		ranking: 12,
		tax_dia: 0,
		tax_ruby: 0,
		trade_tax_rate: "0",
		shop_tax_rate: "20",
		craft_tax_rate: "30",
		territory_count: 1,
		territory_grade: "Garrison",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON01_RONDO",
		guild_member_count: null,
		max_guild_member_count: null,
		guild_id: null,
		guild_name: null,
		guild_level: null,
		guild_master_guid: null,
		guild_master_gc_name: null,
		guild_description: null,
		ranking: null,
		tax_dia: 0,
		tax_ruby: 0,
		trade_tax_rate: "0",
		shop_tax_rate: "20",
		craft_tax_rate: "30",
		territory_count: null,
		territory_grade: "Garrison",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON01_SIGIL",
		guild_member_count: 34,
		max_guild_member_count: 45,
		guild_id: "1301320000000000044",
		guild_name: "영웅",
		guild_level: 42,
		guild_master_guid: "1101300000120000380",
		guild_master_gc_name: "이지스",
		guild_description: "프라시아의 서비스 종료때까지 함께하실분 모심.문의바람",
		ranking: 3,
		tax_dia: 0,
		tax_ruby: 0,
		trade_tax_rate: "0",
		shop_tax_rate: "40",
		craft_tax_rate: "60",
		territory_count: 1,
		territory_grade: "Garrison",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON02_AMINTA",
		guild_member_count: null,
		max_guild_member_count: null,
		guild_id: null,
		guild_name: null,
		guild_level: null,
		guild_master_guid: null,
		guild_master_gc_name: null,
		guild_description: null,
		ranking: null,
		tax_dia: 0,
		tax_ruby: 0,
		trade_tax_rate: "0",
		shop_tax_rate: "20",
		craft_tax_rate: "30",
		territory_count: null,
		territory_grade: "Garrison",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON02_LINESAUF",
		guild_member_count: 17,
		max_guild_member_count: 36,
		guild_id: "1313310000540000005",
		guild_name: "천지창조",
		guild_level: 19,
		guild_master_guid: "1104300002020000003",
		guild_master_gc_name: "월광",
		guild_description: "같이 즐겁게 플레이해요!",
		ranking: 43,
		tax_dia: 0,
		tax_ruby: 0,
		trade_tax_rate: "0",
		shop_tax_rate: "20",
		craft_tax_rate: "30",
		territory_count: 1,
		territory_grade: "Garrison",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON02_RONDO",
		guild_member_count: 34,
		max_guild_member_count: 41,
		guild_id: "1313320000080000000",
		guild_name: "괴도",
		guild_level: 23,
		guild_master_guid: "1113300000120000106",
		guild_master_gc_name: "여자친구",
		guild_description: "50렙 이상/중립/친목/즐겁게 지내요",
		ranking: 25,
		tax_dia: 0,
		tax_ruby: 0,
		trade_tax_rate: "0",
		shop_tax_rate: "20",
		craft_tax_rate: "30",
		territory_count: 1,
		territory_grade: "Garrison",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON02_SIGIL",
		guild_member_count: null,
		max_guild_member_count: null,
		guild_id: null,
		guild_name: null,
		guild_level: null,
		guild_master_guid: null,
		guild_master_gc_name: null,
		guild_description: null,
		ranking: null,
		tax_dia: 0,
		tax_ruby: 0,
		trade_tax_rate: "0",
		shop_tax_rate: "20",
		craft_tax_rate: "30",
		territory_count: null,
		territory_grade: "Garrison",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON03_AMINTA",
		guild_member_count: 45,
		max_guild_member_count: 45,
		guild_id: "1301520000000000043",
		guild_name: "DARKMOON",
		guild_level: 31,
		guild_master_guid: "1101300001700000177",
		guild_master_gc_name: "TL",
		guild_description: "편하게 사냥하세요",
		ranking: 10,
		tax_dia: 0,
		tax_ruby: 0,
		trade_tax_rate: "0",
		shop_tax_rate: "20",
		craft_tax_rate: "30",
		territory_count: 1,
		territory_grade: "Garrison",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON03_KROHN",
		guild_member_count: 45,
		max_guild_member_count: 45,
		guild_id: "1307410000020000005",
		guild_name: "百事可樂",
		guild_level: 36,
		guild_master_guid: "1107400000560000179",
		guild_master_gc_name: "엄지",
		guild_description: "해",
		ranking: 4,
		tax_dia: 0,
		tax_ruby: 0,
		trade_tax_rate: "0",
		shop_tax_rate: "20",
		craft_tax_rate: "30",
		territory_count: 2,
		territory_grade: "Garrison",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON03_LINESAUF",
		guild_member_count: null,
		max_guild_member_count: null,
		guild_id: null,
		guild_name: null,
		guild_level: null,
		guild_master_guid: null,
		guild_master_gc_name: null,
		guild_description: null,
		ranking: null,
		tax_dia: 0,
		tax_ruby: 0,
		trade_tax_rate: "0",
		shop_tax_rate: "20",
		craft_tax_rate: "30",
		territory_count: null,
		territory_grade: "Garrison",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON03_RONDO",
		guild_member_count: 50,
		max_guild_member_count: 50,
		guild_id: "1301320000000000023",
		guild_name: "시티",
		guild_level: 34,
		guild_master_guid: "1107500000000004359",
		guild_master_gc_name: "페르",
		guild_description: "",
		ranking: 5,
		tax_dia: 0,
		tax_ruby: 0,
		trade_tax_rate: "0",
		shop_tax_rate: "20",
		craft_tax_rate: "30",
		territory_count: 1,
		territory_grade: "Garrison",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON04_AMINTA",
		guild_member_count: 43,
		max_guild_member_count: 43,
		guild_id: "1301320000000000001",
		guild_name: "신",
		guild_level: 30,
		guild_master_guid: "1101300000000002673",
		guild_master_gc_name: "휴식",
		guild_description: "추종자 / 공헌 ㄱ",
		ranking: 11,
		tax_dia: 0,
		tax_ruby: 0,
		trade_tax_rate: "0",
		shop_tax_rate: "20",
		craft_tax_rate: "30",
		territory_count: 1,
		territory_grade: "Garrison",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON04_KROHN",
		guild_member_count: null,
		max_guild_member_count: null,
		guild_id: null,
		guild_name: null,
		guild_level: null,
		guild_master_guid: null,
		guild_master_gc_name: null,
		guild_description: null,
		ranking: null,
		tax_dia: 0,
		tax_ruby: 0,
		trade_tax_rate: "0",
		shop_tax_rate: "20",
		craft_tax_rate: "30",
		territory_count: null,
		territory_grade: "Garrison",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON04_LINESAUF",
		guild_member_count: 32,
		max_guild_member_count: 42,
		guild_id: "1301330000000000013",
		guild_name: "쿠쿠",
		guild_level: 34,
		guild_master_guid: "1101300000000000280",
		guild_master_gc_name: "쿠영",
		guild_description: "50렙이상 자유롭게 스탯받고 하실분오세요.",
		ranking: 6,
		tax_dia: 0,
		tax_ruby: 0,
		trade_tax_rate: "0",
		shop_tax_rate: "20",
		craft_tax_rate: "30",
		territory_count: 1,
		territory_grade: "Garrison",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON04_RONDO",
		guild_member_count: 14,
		max_guild_member_count: 36,
		guild_id: "1301110000740000006",
		guild_name: "평화주의자",
		guild_level: 21,
		guild_master_guid: "1101100000040000214",
		guild_master_gc_name: "꼬모닝",
		guild_description: "즐겜유저 모집! 공헌농사꾼 환영~",
		ranking: 33,
		tax_dia: 0,
		tax_ruby: 0,
		trade_tax_rate: "0",
		shop_tax_rate: "20",
		craft_tax_rate: "30",
		territory_count: 1,
		territory_grade: "Garrison",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON05_AMINTA",
		guild_member_count: 16,
		max_guild_member_count: 36,
		guild_id: "1307110001420000009",
		guild_name: "민트",
		guild_level: 20,
		guild_master_guid: "1101500000140004206",
		guild_master_gc_name: "해결사",
		guild_description: "같이 즐겁게 플레이해요!",
		ranking: 37,
		tax_dia: 0,
		tax_ruby: 0,
		trade_tax_rate: "0",
		shop_tax_rate: "20",
		craft_tax_rate: "30",
		territory_count: 1,
		territory_grade: "Garrison",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON05_LINESAUF",
		guild_member_count: 12,
		max_guild_member_count: 38,
		guild_id: "1301320000000000019",
		guild_name: "아오지",
		guild_level: 12,
		guild_master_guid: "1107200000000001503",
		guild_master_gc_name: "불타는오이편지",
		guild_description: "워커홀릭 환영",
		ranking: 0,
		tax_dia: 0,
		tax_ruby: 0,
		trade_tax_rate: "0",
		shop_tax_rate: "20",
		craft_tax_rate: "30",
		territory_count: 1,
		territory_grade: "Garrison",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON05_RONDO",
		guild_member_count: 37,
		max_guild_member_count: 47,
		guild_id: "1313330000020000022",
		guild_name: "놀이동산",
		guild_level: 49,
		guild_master_guid: "1113300000020001195",
		guild_master_gc_name: "로티",
		guild_description: "편안한 분위기, 즐겁게 게임하실분 모셔요",
		ranking: 2,
		tax_dia: 0,
		tax_ruby: 0,
		trade_tax_rate: "0",
		shop_tax_rate: "20",
		craft_tax_rate: "30",
		territory_count: 2,
		territory_grade: "Garrison",
		guild_string_map: {}
	},
	{
		world_group_id: "LIVE_W01",
		world_id: "LIVE_W01_R3",
		territory_id: "GARRISON06_LINESAUF",
		guild_member_count: 9,
		max_guild_member_count: 40,
		guild_id: "1301320000000000055",
		guild_name: "빛",
		guild_level: 25,
		guild_master_guid: "1101300000000000574",
		guild_master_gc_name: "샤나스",
		guild_description: "길~게 같이 가실분~! 단체환영/부캐X 무한자사X",
		ranking: 18,
		tax_dia: 0,
		tax_ruby: 0,
		trade_tax_rate: "0",
		shop_tax_rate: "30",
		craft_tax_rate: "40",
		territory_count: 1,
		territory_grade: "Garrison",
		guild_string_map: {}
	}
];

export default worldData;
