{
	"page2_a":[
		{
			"title":[
				{"title":"獎勵"},
				{"title":"道具說明"}
			],
			"bounce":[
				{"bouncename":"綁定天幣15萬","bouncetext":"遊戲內的通用貨幣。"},
				{"bouncename":"星獸高級銀盒*3","bouncetext":"隨機開出一本初級星獸心法,有概率開出冰封、治癒、必殺等稀有星獸心法。"},
				{"bouncename":"職業項鍊*1","bouncetext":"該職業可用的20等項鍊。"},
				{"bouncename":"職業裝備*1","bouncetext":"該職業可用裝備。"}
			],
			"notices":[
				{"notice":"每個角色只能領取一次。"},
				{"notice":"獎勵將於創立角色後透過郵件配發。"},
				{"notice":"官方保有更改活動內容及相關規定條款之權利，變更事項將於遊戲網站中公告說明。"}
			]
		}
	],
	"page2_b":[
		{
			"title":[
				{"title":""},
				{"title":"道具名稱"},
				{"title":"道具說明"}
			],
			"bounce":[
				{"day_show":1,"day":"第1天","rowspan":2,"bouncename":"青龍位引*1","bouncetext":"聖獸祝福的一種，可以為裝備提供一定的附加屬性的提升。"},
				{"day_show":0,"day":"第1天","rowspan":1,"bouncename":"白虎位引*1","bouncetext":"聖獸祝福的一種，可以為裝備提供一定的附加屬性的提升。"},
				{"day_show":1,"day":"第2天","rowspan":1,"bouncename":"變異夢幻人魚[蛋]*1","bouncetext":"星光耀世的變異星獸蛋，聞所未聞，見所未見。"},
				{"day_show":1,"day":"第3天","rowspan":3,"bouncename":"領域晶章*1","bouncetext":"用於開啟和升級領域無雙技能。"},
				{"day_show":0,"day":"第3天","rowspan":1,"bouncename":"朱雀位引*1","bouncetext":"聖獸祝福的一種，可以為裝備提供一定的附加屬性的提升。"},
				{"day_show":0,"day":"第3天","rowspan":1,"bouncename":"玄武位引*1","bouncetext":"聖獸祝福的一種，可以為裝備提供一定的附加屬性的提升。"},
				{"day_show":1,"day":"第4天","rowspan":1,"bouncename":"鑄能天頁*30","bouncetext":"用於領悟和重鑄無雙技能符文"},
				{"day_show":1,"day":"第5天","rowspan":2,"bouncename":"獸元精華*20","bouncetext":"獸王元魂的精華，蘊含狂暴的能量，是進行血脈屬性升級的必需道具。"},
				{"day_show":0,"day":"第5天","rowspan":1,"bouncename":"焚煉石*20","bouncetext":"佈滿神秘紋路的古樸石頭，是開啟血脈和血脈重鑄的必需道具。"},
				{"day_show":1,"day":"第6天","rowspan":1,"bouncename":"心法金盒*1","bouncetext":"心法金盒，隨機開出一本高級星獸心法。"},
				{"day_show":1,"day":"第7天","rowspan":1,"bouncename":"橙裝圖譜禮盒*1","bouncetext":"橙裝圖譜禮盒，開啟後可隨機獲得本職業橙色七曜石圖譜。"}
			],
			"notices":[
				{"notice":"每個角色只能領取一次。"},
				{"notice":"需要領取第一天的禮包才能領取下一個禮包。"},
				{"notice":"每個禮包領取間隔為24小時。"},
				{"notice":"官方保有更改活動內容及相關規定條款之權利，變更事項將於遊戲網站中公告說明。"}
			]
		}
	],
	"page2_c":[
		{
			"title":[
				{"title":"在線時間(分鐘)"},
				{"title":"道具名稱"},
				{"title":"數量"},
				{"title":"道具說明"}
			],
			"bounce":[
				{"time":10,"num":1,"bouncename":"帝國三星天劵*1","bouncetext":"內含10000綁定天幣"},
				{"time":30,"num":2,"bouncename":"星屑*2","bouncetext":"七曜等裝備強化消耗此道具，根據強化的裝備類型不同消耗的數量有區別"},
				{"time":60,"num":2,"bouncename":"引聖石*2","bouncetext":"對聖獸的祝福進行洗練，使其屬性進行重組"},
				{"time":90,"num":3,"bouncename":"星屑*3","bouncetext":"七曜等裝備強化消耗此道具，根據強化的裝備類型不同消耗的數量有區別"},
				{"time":120,"num":2,"bouncename":"金甲鬼熊封印殘牌*2","bouncetext":"金甲鬼熊封印殘牌，集齊35個坐騎殘片可合成坐騎“金甲鬼熊”"},
				{"time":180,"num":3,"bouncename":"引聖石*3","bouncetext":"對聖獸的祝福進行洗練，使其屬性進行重組"},
				{"time":240,"num":4,"bouncename":"一級寶石盒*4","bouncetext":"一級寶石盒，開啟後可獲得隨機獲得一級寶石一個"}
			],
			"notices":[
				{"notice":"每個角色每日只能領取一次。"},
				{"notice":"每日凌晨6點進行重置，請務必在此之前將在線獎勵領取下來。"},
				{"notice":"官方保有更改活動內容及相關規定條款之權利，變更事項將於遊戲網站中公告說明。"}
			]
		}
	],
	"page2_d":[
		{
			"title":[
				{"title":"條件"},
				{"title":"道具"},
				{"title":"數量"},
				{"title":"是否綁定"},
				{"title":"道具說明"}
			],
			"bounce":[
				{"lev_show":1,"lev":"20級","rowspan":1,"num":5,"bind":"綁定","bouncename":"星脈號角(大)*5","bouncetext":"使用後可以讓世界所有人聽到此發言"},
				{"lev_show":1,"lev":"30級","rowspan":1,"num":2,"bind":"綁定","bouncename":"曜藍星石*2","bouncetext":"遊歷大陸的必備寶物。此乃曜星族使用天外隕石製作而成的，具有定位、傳送（2個位置）的功能。因材料的關係，該物品只能使用3次就無法支撐位移能量的侵蝕！"},
				{"lev_show":1,"lev":"40級","rowspan":2,"num":3,"bind":"綁定","bouncename":"溫泉時限卡(小)*3","bouncetext":"使用後今日泡溫泉的時間可增加10分鐘。"},
				{"lev_show":0,"lev":"40級","rowspan":1,"num":5,"bind":"綁定","bouncename":"焰駒封印殘牌*5","bouncetext":"焰駒封印殘牌，集齊10個坐騎殘片可合成坐騎“幽蓮焰駒”"},
				{"lev_show":1,"lev":"50級","rowspan":2,"num":2,"bind":"綁定","bouncename":"星屑*２","bouncetext":"七曜等裝備強化道具，根據強化類別會有不同的消耗數量。"},
				{"lev_show":0,"lev":"50級","rowspan":1,"num":3,"bind":"綁定","bouncename":"引聖石*3","bouncetext":"對聖獸的祝福進行洗鍊，使屬性重組。"},
				{"lev_show":1,"lev":"60級","rowspan":1,"num":3,"bind":"綁定","bouncename":"靈佑之卷*3","bouncetext":"融合時光之力，受過天衍之靈祝福的神奇卷軸，具有引魂回身的神奇作用。（僅可在副本內使用）"},
				{"lev_show":1,"lev":"70級","rowspan":2,"num":30,"bind":"綁定","bouncename":"焚煉石*30","bouncetext":"血脈試煉任務專屬道具，不可進行其它操作。"},
				{"lev_show":0,"lev":"70級","rowspan":1,"num":30,"bind":"綁定","bouncename":"獸元精華*30","bouncetext":"血脈試煉任務專屬道具，點擊對充斥獸元的異狼使用後，會掉落獸元精華。"}
			],
			"notices":[
				{"notice_s":0,"notice":"每個帳號限領取一次。"},
				{"notice_s":0,"notice":"達成獎勵可下領取，舉例說明：小魔角色等級達成LV60，可獲得LV20、LV30、LV40、LV50、LV60共四種獎勵。"},
				{"notice_s":1,"notice":"每一個等級獎勵限領取一次。",
					"notice_ss":[
						{"a":"第一次配獎時間將於7/12 12:00陸續配發至WEB背包(第一次配發獎勵條件則以7/11 23:59等級為基準)"},
						{"a":"第二次配獎時間將於7/19 18:00陸續配發至WEB背包(第二次配發獎勵條件則以7/19 08:59等級為基準)"}
					]
				},
				{"notice_s":0,"notice":"官方保有更改活動內容及相關規定條款之權利，變更事項將於遊戲網站中公告說明。"}
			]
		}
	],
	"page2_e":[
		{
			"title":[
				{"title":"道具名稱"},
				{"title":"數量"},
				{"title":"是否綁定"},
				{"title":"道具說明"}
			],
			"bounce":[
				{"bind":"綁定","num":5,"bouncename":"逍遙令*5","bouncetext":"完成戰魂聖域城內的任務和歷練給予的獎勵，在[逍遙令使]處可換取各種需求的物品。"}
			],
			"notices":[
				{"notice":"每個帳號只能領取一次獎勵。"},
				{"notice":"獎勵將於7/19 16:00陸續發送到WEB背包。"},
				{"notice":"官方保有更改活動內容及相關規定條款之權利，變更事項將於遊戲網站中公告說明。"}
			]
		}
	],
	"page2_f":[
		{
			"title":[
				{"title":"道具名稱"},
				{"title":"數量"},
				{"title":"是否綁定"},
				{"title":"道具說明"}
			],
			"bounce":[
				{"bind":"綁定","num":3,"bouncename":"團隊召集令*3","bouncetext":"使用後可以向所有團隊成員發起號召，回應召集的團隊成員會瞬間回到自己身邊。"}
			],
			"notices":[
				{"notice":"每個帳號只能領取一次獎勵。"},
				{"notice":"獎勵將於7/19 16:00陸續發送到WEB背包。"},
				{"notice":"官方保有更改活動內容及相關規定條款之權利，變更事項將於遊戲網站中公告說明。"}
			]
		}
	],
	"page2_g":[
		{
			"title":[
				{"title":"道具"},
				{"title":"數量"},
				{"title":"是否綁定"},
				{"title":"道具說明"}
			],
			"bounce":[
				{"bind":"綁定","num":1,"bouncename":"戰友回歸禮包","bouncetext":"內含綁定稱號最狂勇者(永久)、天幣*20萬、靈卷*200、背包擴充令*15、星獸高級銀盒*5、焰駒封印殘牌*5、星屑*5的道具。"}
			],
			"notices":[
				{"notice":"每個帳號只能領取一次。"},
				{"notice":"僅限於CB期間有創角玩家，OB登入才可獲得該獎勵。"},
				{"notice":"獎勵會於登入30分後於陸續發送到WEB背包。"},
				{"notice":"官方保有更改活動內容及相關規定條款之權利，變更事項將於遊戲網站中公告說明。"}
			]
		}
	],
	"page2_h":[
		{
			"title":[
				{"title":""},
				{"title":"道具名稱"},
				{"title":"道具說明"}
			],
			"lev":[
				{"n_show":1,"rowspan":2,"n":"第1名","bouncename":"稱號-璀璨戀痕","bouncetext":"等級排行第一名專屬稱號，在開服排行-等級排行活動結束後，獲得第一名即可獲得此稱號；若稱號附帶屬性加成，佩戴後，方可附加。"},
				{"n_show":0,"rowspan":1,"n":"第1名","bouncename":"鑄能天頁*50","bouncetext":"一種可以激發晶章能量和改變晶章能量屬性的一種天頁，用於領悟和重鑄無雙技能符文用於領悟和重鑄無雙技能符文。"},
				{"n_show":1,"rowspan":1,"n":"第2名","bouncename":"鑄能天頁*40","bouncetext":"一種可以激發晶章能量和改變晶章能量屬性的一種天頁，用於領悟和重鑄無雙技能符文用於領悟和重鑄無雙技能符文。"},
				{"n_show":1,"rowspan":1,"n":"第3名","bouncename":"鑄能天頁*30","bouncetext":"一種可以激發晶章能量和改變晶章能量屬性的一種天頁，用於領悟和重鑄無雙技能符文用於領悟和重鑄無雙技能符文。"},
				{"n_show":1,"rowspan":1,"n":"4-10","bouncename":"鑄能天頁*20","bouncetext":"一種可以激發晶章能量和改變晶章能量屬性的一種天頁，用於領悟和重鑄無雙技能符文用於領悟和重鑄無雙技能符文。"},
				{"n_show":1,"rowspan":1,"n":"11-20","bouncename":"鑄能天頁*10","bouncetext":"一種可以激發晶章能量和改變晶章能量屬性的一種天頁，用於領悟和重鑄無雙技能符文用於領悟和重鑄無雙技能符文。"}
			],
			"power":[
				{"n_show":1,"rowspan":3,"n":"第1名","bouncename":"稱號-永無止境","bouncetext":"戰力排行第一名專屬稱號，在開服排行-戰力排行活動結束後，獲得第一名即可獲得此稱號；若稱號附帶屬性加成，佩戴後，方可附加。"},
				{"n_show":0,"rowspan":1,"n":"第1名","bouncename":"星屑*60","bouncetext":"七曜等裝備強化消耗此道具，根據強化的裝備類型不同消耗的數量有區別。"},
				{"n_show":0,"rowspan":1,"n":"第1名","bouncename":"引聖石*100","bouncetext":"對聖獸的祝福進行洗練，使其屬性進行重組。"},
				{"n_show":1,"rowspan":2,"n":"第2名","bouncename":"星屑*50","bouncetext":"七曜等裝備強化消耗此道具，根據強化的裝備類型不同消耗的數量有區別。"},
				{"n_show":0,"rowspan":1,"n":"第2名","bouncename":"引聖石*80","bouncetext":"對聖獸的祝福進行洗練，使其屬性進行重組。"},
				{"n_show":1,"rowspan":2,"n":"第3名","bouncename":"星屑*40","bouncetext":"七曜等裝備強化消耗此道具，根據強化的裝備類型不同消耗的數量有區別。"},
				{"n_show":0,"rowspan":1,"n":"第3名","bouncename":"引聖石*60","bouncetext":"對聖獸的祝福進行洗練，使其屬性進行重組。"},
				{"n_show":1,"rowspan":2,"n":"4-10名","bouncename":"星屑*30","bouncetext":"七曜等裝備強化消耗此道具，根據強化的裝備類型不同消耗的數量有區別。"},
				{"n_show":0,"rowspan":1,"n":"4-10名","bouncename":"引聖石*40","bouncetext":"對聖獸的祝福進行洗練，使其屬性進行重組。"},
				{"n_show":1,"rowspan":2,"n":"11-20名","bouncename":"星屑*20","bouncetext":"七曜等裝備強化消耗此道具，根據強化的裝備類型不同消耗的數量有區別。"},
				{"n_show":0,"rowspan":1,"n":"11-20名","bouncename":"引聖石*20","bouncetext":"對聖獸的祝福進行洗練，使其屬性進行重組。"},
				{"n_show":1,"rowspan":1,"n":"全民獎勵","bouncename":"星屑*10","bouncetext":"七曜等裝備強化消耗此道具，根據強化的裝備類型不同消耗的數量有區別。"}
			],
			"guild":[
				{"n_show":1,"rowspan":3,"n":"第1名","bouncename":"稱號-不殞不負","bouncetext":"稱號道具，使用後可以獲得稱號：不隕不負。軍團排行第一名專屬稱號，在開服排行-軍團排行活動結束後，獲得第一名即可領取獎勵，獲得此稱號；若稱號附帶屬性加成，佩戴後，方可附加。"},
				{"n_show":0,"rowspan":1,"n":"第1名","bouncename":"軍械令*5","bouncetext":"在加入軍團後，使用該道具，可獲得10點軍械值。"},
				{"n_show":0,"rowspan":1,"n":"第1名","bouncename":"軍功令*10","bouncetext":"在加入軍團後，使用該道具，可獲得30點軍團貢獻。"},
				{"n_show":1,"rowspan":2,"n":"第2名","bouncename":"軍械令*5","bouncetext":"在加入軍團後，使用該道具，可獲得10點軍械值。"},
				{"n_show":0,"rowspan":1,"n":"第2名","bouncename":"軍功令*10","bouncetext":"在加入軍團後，使用該道具，可獲得30點軍團貢獻。"},
				{"n_show":1,"rowspan":2,"n":"第3名","bouncename":"軍械令*5","bouncetext":"在加入軍團後，使用該道具，可獲得10點軍械值。"},
				{"n_show":0,"rowspan":1,"n":"第3名","bouncename":"軍功令*10","bouncetext":"在加入軍團後，使用該道具，可獲得30點軍團貢獻。"},
				{"n_show":1,"rowspan":2,"n":"4-10名","bouncename":"軍械令*5","bouncetext":"在加入軍團後，使用該道具，可獲得10點軍械值。"},
				{"n_show":0,"rowspan":1,"n":"4-10名","bouncename":"軍功令*10","bouncetext":"在加入軍團後，使用該道具，可獲得30點軍團貢獻。"},
				{"n_show":1,"rowspan":2,"n":"11-20名","bouncename":"軍械令*5","bouncetext":"在加入軍團後，使用該道具，可獲得10點軍械值。"},
				{"n_show":0,"rowspan":1,"n":"11-20名","bouncename":"軍功令*10","bouncetext":"在加入軍團後，使用該道具，可獲得30點軍團貢獻。"}
			],
			"item":[
				{"n_show":1,"rowspan":2,"n":"第1名","bouncename":"稱號-蒼之風雲","bouncetext":"稱號道具，使用後可以獲得稱號：蒼之風雲神器排行第一名專屬稱號，在開服排行-神器排行活動結束後，獲得第一名即可領取獎勵，獲得此稱號；若稱號附帶屬性加成，佩戴後，方可附加。"},
				{"n_show":0,"rowspan":1,"n":"第1名","bouncename":"頂級靈源*100","bouncetext":"頂級靈源，使用後可以獲得神器能量50點。"},
				{"n_show":1,"rowspan":1,"n":"第2名","bouncename":"頂級靈源*80","bouncetext":"頂級靈源，使用後可以獲得神器能量50點。"},
				{"n_show":1,"rowspan":1,"n":"第3名","bouncename":"頂級靈源*60","bouncetext":"頂級靈源，使用後可以獲得神器能量50點。"},
				{"n_show":1,"rowspan":1,"n":"4-10名","bouncename":"頂級靈源*40","bouncetext":"頂級靈源，使用後可以獲得神器能量50點。"},
				{"n_show":1,"rowspan":1,"n":"11-20名","bouncename":"頂級靈源*20","bouncetext":"頂級靈源，使用後可以獲得神器能量50點。"},
				{"n_show":1,"rowspan":1,"n":"全民獎勵","bouncename":"頂級靈源*5","bouncetext":"頂級靈源，使用後可以獲得神器能量50點。"}
			],
			"blood":[
				{"n_show":1,"rowspan":4,"n":"第1名","bouncename":"稱號-逆亂星空","bouncetext":"稱號道具，使用後可以獲得稱號：逆亂星空血脈排行第一名專屬稱號，在開服排行-血脈排行活動結束後，獲得第一名即可領取獎勵，獲得此稱號；若稱號附帶屬性加成，佩戴後，方可附加。"},
				{"n_show":0,"rowspan":1,"n":"第1名","bouncename":"天隕傷害(絕)*15","bouncetext":"右鍵點擊使用，可提升傷害3%，持續時間12小時，冷卻時間24小時。"},
				{"n_show":0,"rowspan":1,"n":"第1名","bouncename":"焚煉石*250","bouncetext":"佈滿神秘紋路的古樸石頭，是開啟血脈和血脈重鑄的必需道具。"},
				{"n_show":0,"rowspan":1,"n":"第1名","bouncename":"獸元精華*250","bouncetext":"獸王元魂的精華，蘊含狂暴的能量，是進行血脈屬性升級的必需道具。"},
				{"n_show":1,"rowspan":3,"n":"第2名","bouncename":"天隕傷害(絕)*15","bouncetext":"右鍵點擊使用，可提升傷害3%，持續時間12小時，冷卻時間24小時。"},
				{"n_show":0,"rowspan":1,"n":"第2名","bouncename":"焚煉石*200","bouncetext":"佈滿神秘紋路的古樸石頭，是開啟血脈和血脈重鑄的必需道具。"},
				{"n_show":0,"rowspan":1,"n":"第2名","bouncename":"獸元精華*200","bouncetext":"獸王元魂的精華，蘊含狂暴的能量，是進行血脈屬性升級的必需道具。"},
				{"n_show":1,"rowspan":3,"n":"第3名","bouncename":"天隕傷害(絕)*15","bouncetext":"右鍵點擊使用，可提升傷害3%，持續時間12小時，冷卻時間24小時。"},
				{"n_show":0,"rowspan":1,"n":"第3名","bouncename":"焚煉石*150","bouncetext":"佈滿神秘紋路的古樸石頭，是開啟血脈和血脈重鑄的必需道具。"},
				{"n_show":0,"rowspan":1,"n":"第3名","bouncename":"獸元精華*150","bouncetext":"獸王元魂的精華，蘊含狂暴的能量，是進行血脈屬性升級的必需道具。"},
				{"n_show":1,"rowspan":2,"n":"4-10名","bouncename":"焚煉石*100","bouncetext":"佈滿神秘紋路的古樸石頭，是開啟血脈和血脈重鑄的必需道具。"},
				{"n_show":0,"rowspan":1,"n":"4-10名","bouncename":"獸元精華*100","bouncetext":"獸王元魂的精華，蘊含狂暴的能量，是進行血脈屬性升級的必需道具。"},
				{"n_show":1,"rowspan":2,"n":"11-20名","bouncename":"焚煉石*50","bouncetext":"佈滿神秘紋路的古樸石頭，是開啟血脈和血脈重鑄的必需道具。"},
				{"n_show":0,"rowspan":1,"n":"11-20名","bouncename":"獸元精華*50","bouncetext":"獸王元魂的精華，蘊含狂暴的能量，是進行血脈屬性升級的必需道具。"},
				{"n_show":1,"rowspan":1,"n":"全民獎勵","bouncename":"焚煉石*20","bouncetext":"佈滿神秘紋路的古樸石頭，是開啟血脈和血脈重鑄的必需道具。"}
			],
			"notices":[
				{"notice":"每個角色各排行榜只能獲得一次獎勵。"},
				{"notice":"活動結束後去排行榜界面領取。"},
				{"notice":"官方保有更改活動內容及相關規定條款之權利，變更事項將於遊戲網站中公告說明。"}
			]
		}
	],
	"page2_i":[
		{
			"notices":[
				{"notice":"每個角色每日僅限領取一次祝福。"},
				{"notice":"官方保有更改活動內容及相關規定條款之權利，變更事項將於遊戲網站中公告說明。"}
			]
		}
	]
}